spring:
  application:
    name: demo
  datasource:
    url: jdbc:h2:file:./db/db
    username: sa
    driverClassName: org.h2.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

server.port: 9999
logging.level.spring.demo.demo: debug